---
- name: Download Vagrant package
  get_url:
    url: https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.deb
    dest: "~/vagrant_{{ vagrant_version }}_x86_64.deb"

- name: install vagrant packages
  apt:
    deb: "/home/josh/vagrant_{{ vagrant_version }}_x86_64.deb"
  become: yes
