---
- file:
    state: directory
    path: "{{ vagrant_staging_dir }}/{{ inventory_hostname }}/"
  delegate_to: localhost

- name: Copy playbook to local directory
  copy:
    src: "{{ provisioner_playbook }}"
    dest: "{{ (vagrant_staging_dir, inventory_hostname, provisioner_playbook) | path_join }}"
  delegate_to: localhost

- name: Copy Vagrantfile to local directory
  template:
    src: Vagrantfile.j2
    dest: "{{ vagrant_staging_dir }}/{{ inventory_hostname }}/Vagrantfile"
  delegate_to: localhost
